### ISSUE TITLE
upgrade deps

### ISSUE THREAD

**Issue by Miamoto-Musashi** [romgrm/mimecon_package#1]
pls upgrade deps to newer versions 
thx

**Comment by Miamoto-Musashi** [comment]
there is a pull request for this #2

**Comment by romgrm** [comment]
Hi @Miamoto-Musashi  :) 

Thanks a lot for your contribution. 

I applied your changes and update the package in pub dev. 

Don't hesitate if you see another change to make 🙏

**Comment by Miamoto-Musashi** [comment]
thanks to you for the effort ;)
